.global asm_func1
asm_func1:
    # write below this line 
    #######################
    srli a7, a7, 13
    andi a7, a7, 1
    xori a0, a7, 1


    #######################
    # write above this line 
    ret     # do not remove!

.global asm_func2
asm_func2:
    # write below this line 
    #######################



    #######################
    # write above this line 
    ret     # do not remove!

.global asm_func3
asm_func3:
    # write below this line 
    #######################

    

    #######################
    # write above this line 
    ret     # do not remove!